name: Docker Image Scan

on:
  workflow_dispatch:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *' 

jobs:
  scan:
    name: Run Trivy vulnerability scanner on Docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - 'openjdk:11-jdk'
          - 'amazoncorretto:11-al2023'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner for ${{ matrix.docker_image }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.docker_image }}
          vuln-type: 'os,library'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'